# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=datawow

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_MAX_AGE=${SESSION_MAX_AGE}
      - SESSION_RESAVE=${SESSION_RESAVE}
      - SESSION_SAVE_UNINITIALIZED=${SESSION_SAVE_UNINITIALIZED}
      - NEST_DEBUG=${NEST_DEBUG}
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./src:/app/src